version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    # command: >
    #   sh -c "python manage.py wait_for_db &&
    #          python manage.py migrate &&
    #          python manage.py runserver 0.0.0.0:8000"
    command: >
      sh -c "python ./main.py"
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=flask_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres2
      - POSTGRES_PORT=5432